# Generated by Django 2.0.6 on 2019-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
