# Generated by Django 2.0.6 on 2019-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_delete_taskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardhistory',
            name='message',
        ),
        migrations.AlterField(
            model_name='forwardhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
