class Constant():
    MAIL_AUTH_STATUS_INIT = '0'
    MAIL_AUTH_STATUS_SENT = '1'
    MAIL_AUTH_STATUS_DONE = '2'

    FORWARD_TARGET_STOP = '0'
    FORWARD_TARGET_COUNT = '1'
    FORWARD_TARGET_SUBJECT = '2'
    FORWARD_TARGET_MAIL = '3'

    FORWARD_STATUS_INIT = '0'
    FORWARD_STATUS_VALID = '1'
    FORWARD_STATUS_AUTH_FAILURE = '2'
    FORWARD_STATUS_INVALID = '3'
